### ISSUE TITLE
Configuración del ambiente de desarrollo

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CallCenter#2]

**Comment by lenaval73** [comment]
Tarea terminada. Se compilaron los 3 proyectos .

![image](https://user-images.githubusercontent.com/23709673/37812537-2ecd0e9e-2e26-11e8-8fd4-e814979eb575.png)

![image](https://user-images.githubusercontent.com/23709673/37812553-4737ec60-2e26-11e8-80e6-fbf36941d750.png)
