### ISSUE TITLE
Integración SigaMetClasses.frmConTarjetaCredito en módulo de call center

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CallCenter#7]
# ------ESPECIFICACIONES------

## Requisitos:
- Descargar el repositorio de callcenter y compilar
- Descargar el repositorio de SigametLibrerias y compilar SigametClasses

## Procedimiento
1. Descargar la versión más reciente de la rama **development**  de CallCenter
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Referenciar la versión más reciente de SigametClasses
4. Modificar el método frmCallcenter.CapturaTarjeta para recuperar el valor del parámetro URLGateway
5. Si el valor del parámetro del punto anterior 
 a) Es vacío o no se encuentra configurado, entonces invocar el constructor New SigaMetClasses.frmConTarjetaCredito(_Cliente, GLOBAL_Usuario)
 b) Se encuentra configurado y no es vacío invocar el constructor sobrecargado New SigaMetClasses.frmConTarjetaCredito(_Cliente, GLOBAL_Usuario, URLGateway)

**Comment by lenaval73** [comment]
![image](https://user-images.githubusercontent.com/23709673/38150790-f12b5e58-341d-11e8-975c-d468602f6f4d.png)
![image](https://user-images.githubusercontent.com/23709673/38150839-1de749ac-341e-11e8-91b9-e7c8a5c24c01.png)

**Comment by lenaval73** [comment]
![image](https://user-images.githubusercontent.com/23709673/38150858-30abd788-341e-11e8-94ac-bf77eb1af8d8.png)

![image](https://user-images.githubusercontent.com/23709673/38150892-53661dd8-341e-11e8-8a59-2d55a372945d.png)

**Comment by lenaval73** [comment]
![image](https://user-images.githubusercontent.com/23709673/38150923-72227406-341e-11e8-84e2-5aca9c64cfa3.png)

**Comment by lenaval73** [comment]
![image](https://user-images.githubusercontent.com/23709673/38150935-7f2ab014-341e-11e8-87ab-e977862349ae.png)

**Comment by lenaval73** [comment]
![image](https://user-images.githubusercontent.com/23709673/38150958-91f7ae04-341e-11e8-9a4b-bc4858da6c3d.png)

![image](https://user-images.githubusercontent.com/23709673/38150981-a52e2ff2-341e-11e8-800b-82e244c38b7d.png)
