### ISSUE TITLE
Boletín

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/CallCenter#8]
# ------ESPECIFICACIONES------

## Requisitos:
- Las modificaciones serán realizadas en el repositorio CallCenter

![image](https://user-images.githubusercontent.com/30910881/37567217-428a8a06-2a89-11e8-96cf-6d2169a50e70.png)

## Procedimiento
1. Descargar la versión más reciente de la rama **development**
2. Crear una rama de tipo **Feature** a partir de la rama **development**
3. Modificar la pantalla frmBoletin, sobrecargando su constructor que ahora recibirá un parámetro tipo string llamado URLGateway
4. Crear un miembro privado de tipo String llamado **_URLGateway** y cargarlo en el constructor del formulario descrito en el punto número tres
5. Sobrecargar el método  **CargaBoletin** para que reciba el parámetro **URLGateway** de tipo String
6. En el método sobrecargado crear una instancia de la estructura **SolicitudPedidoGateway** a la que se le pasará el valor de fecha de pedido desde el control **dtpFecha** y la célula desde el control **cboUsuarioCelula**
7. Crear el método privado **ConsultaClientesBoletinCRM** (List<RTGMCore.Pedido>) y regresará el tipo List<ListViewItem> con los siguientes miembros:
                oItem = New ListViewItem(CType(dr("PedidoReferencia"), String).Trim, tipo) '0
                oItem.SubItems.Add(CType(dr("AñoPed"), Short).ToString) '1
                oItem.SubItems.Add(CType(dr("Celula"), Byte).ToString) '2
                oItem.SubItems.Add(CType(dr("Pedido"), Integer).ToString) '3
                oItem.SubItems.Add(CType(dr("Ruta"), Short).ToString) '4
                oItem.SubItems.Add(CType(dr("RutaDescripcion"), String).Trim) '5
                oItem.SubItems.Add(CType(dr("RutaBoletin"), Short).ToString) '6
                oItem.SubItems.Add(CType(dr("RutaDescripcionBoletin"), String).Trim) '7
                oItem.SubItems.Add(CType(dr("FAlta"), Date).ToString) '8
                oItem.SubItems.Add(CType(dr("FCompromiso"), Date).ToShortDateString) '9
                oItem.SubItems.Add(CType(dr("Cliente"), String)) '10
                oItem.SubItems.Add(CType(dr("Nombre"), String).Trim) '11
                oItem.SubItems.Add(CType(dr("DireccionCompleta"), String).Trim) '12
                oItem.SubItems.Add(CType(dr("PrioridadPedidoDescripcion"), String).Trim) '13
                oItem.SubItems.Add(CType(dr("Usuario"), String).Trim) '14
                oItem.SubItems.Add(CType(dr("StatusBoletin"), String).Trim) '15
                oItem.SubItems.Add(CType(dr("Insistente"), String).Trim) '16
                oItem.SubItems.Add(CType(dr("TelCasa"), String).Trim) '17
                oItem.SubItems.Add(CType(dr("Observaciones"), String).Trim) '18

8. La función del método definido en el punto seis será la de recorrer la colección de entrada elemento por elemento y recuperar el ID del cliente del pedido, con ese valor invocar una instancia del método 
**buscarDireccionEntrega** para tomar **respuesta.Nombre** y actualizar al subItem **Nombre** del punto anterior
9. Cargar con los datos devueltos por el método ConsultaClientesBoletinCRM el listview llamado lvwBoletin

10. En los once puntos en los que se llama a la función CargaBoletin decidir mediante una sentencia IF:
 a) Sí el valor de _URLGateway inválido, nulo o vacío entonces llamar a CargarBoletin sin parámetros
 b) Sí el valor de _URLGateway es válido entonces llamar a CargarBoletin con parámetro

## Criterios de aceptación:
i) El formulario debe funcionar con ambos constructores
ii) Si el parámetro URLGateway es nulo o vacío (aplicar trim) debe cerrarse el formulario y lanzar la excepción descrita
iii) Si el parámetro URLGateway es correcto debe mostrarse el formulario desplegando los datos que provienen del servicio web
iv) Los once flujos que llaman CargaBoletin deberán ser probados con o sin valor de parámetro

**Comment by lenaval73** [comment]
Sin parámetro..  
![image](https://user-images.githubusercontent.com/23709673/38149861-a1730518-3419-11e8-909c-66c431b16f40.png)

![image](https://user-images.githubusercontent.com/23709673/38149919-d4210334-3419-11e8-9745-944c41c15af0.png)

![image](https://user-images.githubusercontent.com/23709673/38150093-9a02d244-341a-11e8-92e2-969c344f0978.png)

**Comment by lenaval73** [comment]
Flujo con Parámetro prendido..
![image](https://user-images.githubusercontent.com/23709673/38150117-b2d2ebba-341a-11e8-86c7-f19a4d5fc851.png)

![image](https://user-images.githubusercontent.com/23709673/38150167-eda8f90a-341a-11e8-816e-ef77d68b2068.png)
![image](https://user-images.githubusercontent.com/23709673/38150336-a7df5bde-341b-11e8-8fd8-3c97d0e667a0.png)


![image](https://user-images.githubusercontent.com/23709673/38150549-b0e6df6c-341c-11e8-91c7-da135a487f8b.png)
![image](https://user-images.githubusercontent.com/23709673/38150562-bed0753e-341c-11e8-8561-ceffdeb35f75.png)

![image](https://user-images.githubusercontent.com/23709673/38150572-d1112018-341c-11e8-97ba-c6c5e0ad0da7.png)
![image](https://user-images.githubusercontent.com/23709673/38150615-16cbddf0-341d-11e8-916f-3387e8d1d2ac.png)
